### PR TITLE
Please check commit message

### PR DESCRIPTION
**Pull request by z3t0**
**README:**
    -Made easier to read
    -Added more install instructions
    -Added Features section
**syntax/arduino.vim:**
    -Updated to 1.5.8 support
    -Cleaned up unnecessary differentiations (e.g using arduinoFunc and
     arduinoMethod when both are mapped to Function)
    -Added USB functions (keyboard and mouse)
    -Added Operators (+,<, etc)

Please add me to the contributors so I can write straight to the repo, Thank.

### CODE REVIEW

**Comment by sudar** [comment]
@z3t0 Thanks for the pull request, but right now it results in a merge conflict. Can you look into it?

I see that you have added support for Arduino 1.5.8, but is Arduino 1.0.x still supported? If yes then we don't have to do anything. If no then we may have to put Arduino 1.5.x support in a separate branch.

Also did you hand craft the syntax file? 

I will go over the commit and will let you know if I have any more comments.

**Comment by z3t0** [comment]
I'll look into the merge conflict, Arduino 1.0.x should still be supported but I'll look into the changelogs to make sure.

Yes I did handcraft it, it's my first time making a syntax file so I wanted to learn the "inner workings"

Can we move over to https://github.com/z3t0/vim-arduino-syntax-2

I am currently almost done making it possible to include all plugins, getting super excited but might not finish it tonight - fixing a few annoying bugs

**Comment by sudar** [comment]
> I'll look into the merge conflict, 

I think the merge conflict is because of your earlier pull request where you modified the readme file.

> Arduino 1.0.x should still be supported but I'll look into the changelogs to make sure.

Thanks. There are lot of people who are currently using this and I don't want to break it for them.

> Yes I did handcraft it, it's my first time making a syntax file so I wanted to learn the "inner workings"

Thanks.

> Can we move over to https://github.com/z3t0/vim-arduino-syntax-2. I am currently almost done making it possible to include all plugins, getting super excited but might not finish it tonight - fixing a few annoying bugs

Well, I have been actively using this project for more than 2 years and have linked it in countless places and I don't want to abandon the project :) Also there is a slightly heavy userbase for this project as well, so I don't want to break anything for them.

If at any point I decide to abandon the project then I will transfer it to you :) Also in git (unlike svn) there is no concept of centralised repository so I think it doesn't really matter under who's name the project is present.

Meanwhile thank you for all your contribution and interest in this project. Once we merge this pull request, I would be happy to add you as a collaborator, provided both of us send our changes as pull request and merge it only after getting it reviewed by the other one.

**Comment by z3t0** [comment]
OK no problem, I'll push my other changes to you as soon as I get it stable.

**Comment by sudar** [comment]
> OK no problem, I'll push my other changes to you as soon as I get it stable.

Great. Thanks for the understanding.

**Comment by z3t0** [comment]
Just an update, its 95% complete there's one more error I have to fix but I gotta go sleep now. It should be fixed with 5 minutes of tinkering.

**Comment by z3t0** [comment]
OH nevermind. ITS COMPELTE. I just need to figure out how to use formatters now... Should be easy actually. (too bad I have near zero experience on python lol)

**Comment by z3t0** [comment]
Would mind adding me on hangouts (google talk)so we can chat about the
repo, github doesn't have pm and it's kinda pointless to list all our ideas
on the merge request

Add: zetoslab@gmail.com

**Comment by z3t0** [comment]
I just checked the changelog and there are minor changes that will be
annoying for users, so I suggest merging this into a new branch while its
in beta. I'll look into options so we can support both versions from one
file

**Comment by sudar** [comment]
> Would mind adding me on hangouts (google talk)so we can chat about the
repo, github doesn't have pm and it's kinda pointless to list all our ideas
on the merge request Add: zetoslab@gmail.com

If the discussion is related to the pull request then we can discuss it in the pull request itself. If not then you can talk to me over Google Hangout at 'sudar@sudarmuthu.com'

> I just checked the changelog and there are minor changes that will be
annoying for users, so I suggest merging this into a new branch while its
in beta. I'll look into options so we can support both versions from one
file

Can you briefly explain what is the change that we need to address?

> OH nevermind. ITS COMPELTE. I just need to figure out how to use formatters now... Should be easy actually. (too bad I have near zero experience on python lol)

Let me know if you need any help with Python.

**Comment by z3t0** [comment]
As for the changes there are minor things like boolean got renamed as bool and alot of other things that aren't exactly worth mentioning (just take a look at the changelogs and you'll see what I mean)

Here's the python script, I'm out but see what you can do.
https://github.com/z3t0/vim-arduino-syntax-gen

**Comment by z3t0** [comment]
I think we should merge this into a new branch.

The python script is almost complete (it's completely rewritten and not like the one in the repo)
I will upload it to the repo I mentioned once its complete, how do you plan on incorporating it into this repo?

Basically its a python script than generates the syntax file for you, including libraries.

Lemme know what you think.

**Comment by z3t0** [comment]
I'll make a new pull request. Please add me as contributor

**Pull request closed without merging**
