### PR TITLE
Added definitions for Arduino 1.6.0

### PR DESCRIPTION
**Pull request by z3t0**
Please review this PR as it should be stable. This was generated using my [arduvim](github.com/z3t0/arduvim) plugin so for the best support please install that and use it because it generates syntax definitions on the go.

### CODE REVIEW

**Comment by z3t0** [comment]
@Jaidan please take a look at this PR and also the plugin mentioned above.

**Comment by sudar** [comment]
@z3t0 This pull request still has some issues.

I have commented about it in the commit.

**Comment by z3t0** [comment]
@sudar Please take a look at merging the README as well, since it is much more informative and also  has more install instructions.

**Comment by z3t0** [comment]
As discussed previously, the reason that there is no point in library specific definitions which have been remove in 9edc739 is because they cannot be used to turn Library syntax on or off. If we want this functionality then the best sustainable approach is in a full-sized plugin, I will add it to the TODO on my plugin and work on implementing it.

**Comment by sudar** [comment]
@z3t0 This pull request has the following issues.

- Highlights are defined for arduinoStdFunc, arduinoMethod, arduinoIdentifier, arduinoOperator but they are not present in the syntax files.
- Serial Serial1 Serial2 Serial3 etc should be highlighted as Identifier and not as functions.

**Comment by z3t0** [comment]
@sudar I will take a look and make another commit once I work through the above mentioned issues. Thanks for the feedback!

**Comment by z3t0** [comment]
@sudar I apologize for the delay, exciting things going on at voxel.js!

**Comment by sudar** [comment]
No problem. Take your time.

**Comment by z3t0** [comment]
@sudar OK, the latest commit should fix things

**Comment by sudar** [comment]
@z3t0 Thanks for fixing it.

This PR was not merging, so I picked your changes and committed them.

I have added your name in credit section of both in the syntax file and the in the README file.

Thanks for all the hard work.

**Pull request closed without merging**
